kind: pipeline
type: docker
name: en

steps:
- name: greeting
  image: alpine
  commands:
  - shivam

---
kind: pipeline
type: docker
name: fr

steps:
- name: greeting
  image: alpine
  commands:
  - echo bonjour monde
