kind: pipeline
type: kubernetes
name: en

steps:
- name: greeting
  image: alpine
  commands:
  - cd shivam

---
kind: pipeline
type: kubernetes
name: fr

steps:
- name: greeting
  image: alpine
  commands:
  - echo bonjour monde
